# Generated by Django 3.2.9 on 2021-12-10 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employzapp', '0003_alter_occupation_fire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occupation',
            name='fire_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата увольнения'),
        ),
    ]
